<a href="https://colab.research.google.com/github/vinayak1920/Project/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [ ]:
!unzip archive.zip

Archive:  archive.zip
replace austin_weather.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [ ]:
data = pd.read_csv("austin_weather.csv")
data.head()

Date  TempHighF  ...  PrecipitationSumInches               Events
0  2013-12-21         74  ...                    0.46  Rain , Thunderstorm
1  2013-12-22         56  ...                       0                     
2  2013-12-23         58  ...                       0                     
3  2013-12-24         61  ...                       0                     
4  2013-12-25         58  ...                       T                     

[5 rows x 21 columns]

In [ ]:
data = data.drop(
    ['Events', 'Date', 'SeaLevelPressureHighInches', 'SeaLevelPressureLowInches'], axis=1)
data = data.replace('T', 0.0)
data = data.replace('-', 0.0)
data.to_csv('austin_clean.csv')

In [ ]:
data = pd.read_csv("austin_clean.csv")

X = data.drop(['PrecipitationSumInches'], axis=1)

Y = data['PrecipitationSumInches']
Y = Y.values.reshape(-1, 1)
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(X, Y, test_size = 0.2)

day_index = 798
days = [i for i in range(Y.size)]

clf = LinearRegression()
clf.fit(x_train, y_train)

inp = np.array([[74], [60], [45], [67], [49], [43], [33], [45],
                [57], [29.68], [10], [7], [2], [0], [20], [4], [31]])

inp = inp.reshape(1, -1)
clf.score(x_test, y_test)

0.24832672933066757

In [ ]:
print('The precipitation in inches for the input is:', clf.predict(inp))

print('The precipitation trend graph: ')
plt.scatter(days, Y, color='g')
plt.scatter(days[day_index], Y[day_index], color='r')
plt.title('Precipitation level')
plt.xlabel('Days')
plt.ylabel('Precipitation in inches')

The precipitation in inches for the input is: [[1.33868402]]
The precipitation trend graph: 


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


Text(0, 0.5, 'Precipitation in inches')

In [ ]:
x_f = X.filter(['TempAvgF', 'DewPointAvgF', 'HumidityAvgPercent',
                'SeaLevelPressureAvgInches', 'VisibilityAvgMiles',
                'WindAvgMPH'], axis=1)
print('Preciptiation Vs Selected Attributes Graph: ')
for i in range(x_f.columns.size):
    plt.subplot(3, 2, i+1)
    plt.scatter(days, x_f[x_f.columns.values[i][:100]], color='g')
    plt.scatter(days[day_index], x_f[x_f.columns.values[i]]
                [day_index], color='r')
    plt.title(x_f.columns.values[i])

plt.show()

Preciptiation Vs Selected Attributes Graph: 


# New Section

In [ ]:
dset = pd.read_csv("austin_clean.csv")
dset

Unnamed: 0  TempHighF  ...  WindGustMPH  PrecipitationSumInches
0              0         74  ...         31.0                    0.46
1              1         56  ...         25.0                    0.00
2              2         58  ...         12.0                    0.00
3              3         61  ...         20.0                    0.00
4              4         58  ...         16.0                    0.00
...          ...        ...  ...          ...                     ...
1314        1314        103  ...         21.0                    0.00
1315        1315        105  ...         20.0                    0.00
1316        1316        107  ...         17.0                    0.00
1317        1317        106  ...         20.0                    0.00
1318        1318         99  ...         20.0                    0.00

[1319 rows x 18 columns]

In [ ]:
x = np.array(dset.drop(["PrecipitationSumInches"], 1))
y = np.array(dset["PrecipitationSumInches"])
print(x)
print(y)

[[0.000e+00 7.400e+01 6.000e+01 ... 2.000e+01 4.000e+00 3.100e+01]
 [1.000e+00 5.600e+01 4.800e+01 ... 1.600e+01 6.000e+00 2.500e+01]
 [2.000e+00 5.800e+01 4.500e+01 ... 8.000e+00 3.000e+00 1.200e+01]
 ...
 [1.316e+03 1.070e+02 9.200e+01 ... 1.200e+01 4.000e+00 1.700e+01]
 [1.317e+03 1.060e+02 9.300e+01 ... 1.300e+01 4.000e+00 2.000e+01]
 [1.318e+03 9.900e+01 8.800e+01 ... 1.200e+01 4.000e+00 2.000e+01]]
[0.46 0.   0.   ... 0.   0.   0.  ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [ ]:
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(x, y, test_size = 0.2)
rain_predict_linear = LinearRegression()
rain_predict_linear.fit(x_train, y_train)


LinearRegression()

In [ ]:
acc_linear = rain_predict_linear.score(x_test, y_test)
acc_linear

0.2920763845361726

# Polynomial Regression


In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=5)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.fit_transform(x_test)

In [ ]:
rain_predict_poly = LinearRegression()
rain_predict_poly.fit(x_train_poly, y_train)
acc_poly = rain_predict_poly.score(x_test_poly, y_test)

In [ ]:
acc_poly

-493.5306814526274

# SVM

In [ ]:
svmset = pd.read_csv("austin_weather.csv")
s = set(svmset["Events"])
s

{' ',
 'Fog',
 'Fog , Rain',
 'Fog , Rain , Thunderstorm',
 'Fog , Thunderstorm',
 'Rain',
 'Rain , Snow',
 'Rain , Thunderstorm',
 'Thunderstorm'}

In [ ]:
svmset

Date  TempHighF  ...  PrecipitationSumInches               Events
0     2013-12-21         74  ...                    0.46  Rain , Thunderstorm
1     2013-12-22         56  ...                       0                     
2     2013-12-23         58  ...                       0                     
3     2013-12-24         61  ...                       0                     
4     2013-12-25         58  ...                       T                     
...          ...        ...  ...                     ...                  ...
1314  2017-07-27        103  ...                       0                     
1315  2017-07-28        105  ...                       0                     
1316  2017-07-29        107  ...                       0                     
1317  2017-07-30        106  ...                       0                     
1318  2017-07-31         99  ...                       0                     

[1319 rows x 21 columns]

In [ ]:
clfset =  svmset.drop(
    ['Date', 'SeaLevelPressureHighInches', 'SeaLevelPressureLowInches', "PrecipitationSumInches"], axis=1)
clfset = clfset.replace('-', 0.0)

x = np.array(clfset.drop(['Events'], 1))
y = np.array(clfset['Events'])

le = sk.preprocessing.LabelEncoder()
sl = le.fit_transform(list(s))
sl

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """


array([4, 1, 3, 8, 7, 5, 2, 0, 6])

In [ ]:
y = le.fit_transform(list(y))

In [ ]:
set_ = set()

In [ ]:
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(x, y, test_size = 0.2)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(x_train, y_train)
acc_knn = knn.score(x_test, y_test)
acc_knn

0.7537878787878788

# SVM

In [ ]:
from sklearn import svm

svm_weather = svm.SVC(kernel='linear', C=2)
svm_weather.fit(x_train, y_train)
acc_svm = svm_weather.score(x_test, y_test)
acc_svm

0.7992424242424242

# QSVM Simple